name: Python Application CI

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  build:
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.10]  

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10 

      - name: Verify Python Version
        run: python --version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install the package in development mode
        run: |
          pip install -e .

      - name: Run tests
        run: |
          python -m unittest discover -s tests

      - name: Lint code
        run: |
          pip install flake8
          flake8 .

      - name: Check code formatting
        run: |
          pip install black
          black --check .

      - name: Check for security vulnerabilities
        run: |
          pip install safety
          safety check
